export default {
  FETCH_FILM_REQUEST: 'FETCH_FILM_REQUEST',
  FETCH_FILM_SUCCESS: 'FETCH_FILM_SUCCESS',
  FETCH_PERSON_REQUEST: 'FETCH_PERSON_REQUEST',
  FETCH_PERSON_SUCCESS: 'FETCH_PERSON_SUCCESS'
}
